// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: protos/platform/ptype/page.proto

package ptype

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: `validate:"gte=1"`
	Index int64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// @inject_tag: `validate:"gt=0,max=1000"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_platform_ptype_page_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_protos_platform_ptype_page_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_protos_platform_ptype_page_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Page) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PageCtx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Size  int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// total record number, not page number
	Total int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *PageCtx) Reset() {
	*x = PageCtx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_platform_ptype_page_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageCtx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageCtx) ProtoMessage() {}

func (x *PageCtx) ProtoReflect() protoreflect.Message {
	mi := &file_protos_platform_ptype_page_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageCtx.ProtoReflect.Descriptor instead.
func (*PageCtx) Descriptor() ([]byte, []int) {
	return file_protos_platform_ptype_page_proto_rawDescGZIP(), []int{1}
}

func (x *PageCtx) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PageCtx) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageCtx) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_protos_platform_ptype_page_proto protoreflect.FileDescriptor

var file_protos_platform_ptype_page_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2f, 0x70, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x45, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02,
	0x28, 0x01, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x22, 0x05, 0x18, 0xe8,
	0x07, 0x20, 0x00, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x49, 0x0a, 0x07, 0x50, 0x61, 0x67,
	0x65, 0x43, 0x74, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x2e, 0x79, 0x75, 0x61, 0x6e,
	0x73, 0x75, 0x61, 0x6e, 0x2e, 0x63, 0x6e, 0x2f, 0x73, 0x73, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x74, 0x79, 0x70,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_platform_ptype_page_proto_rawDescOnce sync.Once
	file_protos_platform_ptype_page_proto_rawDescData = file_protos_platform_ptype_page_proto_rawDesc
)

func file_protos_platform_ptype_page_proto_rawDescGZIP() []byte {
	file_protos_platform_ptype_page_proto_rawDescOnce.Do(func() {
		file_protos_platform_ptype_page_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_platform_ptype_page_proto_rawDescData)
	})
	return file_protos_platform_ptype_page_proto_rawDescData
}

var file_protos_platform_ptype_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_platform_ptype_page_proto_goTypes = []interface{}{
	(*Page)(nil),    // 0: ptype.Page
	(*PageCtx)(nil), // 1: ptype.PageCtx
}
var file_protos_platform_ptype_page_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_platform_ptype_page_proto_init() }
func file_protos_platform_ptype_page_proto_init() {
	if File_protos_platform_ptype_page_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_platform_ptype_page_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_platform_ptype_page_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageCtx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_platform_ptype_page_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_platform_ptype_page_proto_goTypes,
		DependencyIndexes: file_protos_platform_ptype_page_proto_depIdxs,
		MessageInfos:      file_protos_platform_ptype_page_proto_msgTypes,
	}.Build()
	File_protos_platform_ptype_page_proto = out.File
	file_protos_platform_ptype_page_proto_rawDesc = nil
	file_protos_platform_ptype_page_proto_goTypes = nil
	file_protos_platform_ptype_page_proto_depIdxs = nil
}
