// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: protos/platform/protoconsts/protoconsts.proto

package protoconsts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用量刷新规则
type RefreshType int32

const (
	RefreshType_TYPE_NO      RefreshType = 0
	RefreshType_TYPE_DAILY   RefreshType = 1
	RefreshType_TYPE_MONTHLY RefreshType = 30
	RefreshType_TYPE_YEARLY  RefreshType = 365
	RefreshType_TYPE_FIXDATE RefreshType = 9999
)

// Enum value maps for RefreshType.
var (
	RefreshType_name = map[int32]string{
		0:    "TYPE_NO",
		1:    "TYPE_DAILY",
		30:   "TYPE_MONTHLY",
		365:  "TYPE_YEARLY",
		9999: "TYPE_FIXDATE",
	}
	RefreshType_value = map[string]int32{
		"TYPE_NO":      0,
		"TYPE_DAILY":   1,
		"TYPE_MONTHLY": 30,
		"TYPE_YEARLY":  365,
		"TYPE_FIXDATE": 9999,
	}
)

func (x RefreshType) Enum() *RefreshType {
	p := new(RefreshType)
	*p = x
	return p
}

func (x RefreshType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefreshType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_platform_protoconsts_protoconsts_proto_enumTypes[0].Descriptor()
}

func (RefreshType) Type() protoreflect.EnumType {
	return &file_protos_platform_protoconsts_protoconsts_proto_enumTypes[0]
}

func (x RefreshType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefreshType.Descriptor instead.
func (RefreshType) EnumDescriptor() ([]byte, []int) {
	return file_protos_platform_protoconsts_protoconsts_proto_rawDescGZIP(), []int{0}
}

// 资源类型
type ResourceType int32

const (
	ResourceType_UNKNOWN ResourceType = 0
	// 计算软件
	ResourceType_COMPUTE_APP ResourceType = 1
	// 可视化软件
	ResourceType_VISUAL_APP ResourceType = 2
	// 云存储
	ResourceType_CLOUD_STORAGE ResourceType = 3
	// 超算命令行软件
	ResourceType_SC_TERMINAL_APP ResourceType = 4
	// 云应用 2.0 硬件/软件
	ResourceType_IBV_SOFTWARE ResourceType = 5
	ResourceType_IBV_HARDWARE ResourceType = 6
	// 标准计算应用
	ResourceType_STANDARD_COMPUTE_APP ResourceType = 7
	// 计费套餐
	// 可视化全局套餐(包含所有可视化应用)
	ResourceType_BUNDLE_VISUAL_APP_ALL ResourceType = 101
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "COMPUTE_APP",
		2:   "VISUAL_APP",
		3:   "CLOUD_STORAGE",
		4:   "SC_TERMINAL_APP",
		5:   "IBV_SOFTWARE",
		6:   "IBV_HARDWARE",
		7:   "STANDARD_COMPUTE_APP",
		101: "BUNDLE_VISUAL_APP_ALL",
	}
	ResourceType_value = map[string]int32{
		"UNKNOWN":               0,
		"COMPUTE_APP":           1,
		"VISUAL_APP":            2,
		"CLOUD_STORAGE":         3,
		"SC_TERMINAL_APP":       4,
		"IBV_SOFTWARE":          5,
		"IBV_HARDWARE":          6,
		"STANDARD_COMPUTE_APP":  7,
		"BUNDLE_VISUAL_APP_ALL": 101,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_platform_protoconsts_protoconsts_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_protos_platform_protoconsts_protoconsts_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_protos_platform_protoconsts_protoconsts_proto_rawDescGZIP(), []int{1}
}

var File_protos_platform_protoconsts_protoconsts_proto protoreflect.FileDescriptor

var file_protos_platform_protoconsts_protoconsts_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2a, 0x61, 0x0a, 0x0b,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x44, 0x41, 0x49, 0x4c, 0x59, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x4c, 0x59, 0x10, 0x1e, 0x12, 0x10, 0x0a, 0x0b, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x59, 0x45, 0x41, 0x52, 0x4c, 0x59, 0x10, 0xed, 0x02, 0x12, 0x11, 0x0a, 0x0c,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x58, 0x44, 0x41, 0x54, 0x45, 0x10, 0x8f, 0x4e, 0x2a,
	0xbd, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x56, 0x49, 0x53, 0x55, 0x41, 0x4c, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x02, 0x12, 0x11,
	0x0a, 0x0d, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x10,
	0x03, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x43, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x4c,
	0x5f, 0x41, 0x50, 0x50, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x42, 0x56, 0x5f, 0x53, 0x4f,
	0x46, 0x54, 0x57, 0x41, 0x52, 0x45, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x42, 0x56, 0x5f,
	0x48, 0x41, 0x52, 0x44, 0x57, 0x41, 0x52, 0x45, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x54,
	0x41, 0x4e, 0x44, 0x41, 0x52, 0x44, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x41,
	0x50, 0x50, 0x10, 0x07, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x55, 0x4e, 0x44, 0x4c, 0x45, 0x5f, 0x56,
	0x49, 0x53, 0x55, 0x41, 0x4c, 0x5f, 0x41, 0x50, 0x50, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x65, 0x42,
	0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x75,
	0x61, 0x6e, 0x73, 0x75, 0x61, 0x6e, 0x2f, 0x74, 0x69, 0x63, 0x70, 0x2f, 0x69, 0x50, 0x61, 0x61,
	0x53, 0x2f, 0x73, 0x73, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_platform_protoconsts_protoconsts_proto_rawDescOnce sync.Once
	file_protos_platform_protoconsts_protoconsts_proto_rawDescData = file_protos_platform_protoconsts_protoconsts_proto_rawDesc
)

func file_protos_platform_protoconsts_protoconsts_proto_rawDescGZIP() []byte {
	file_protos_platform_protoconsts_protoconsts_proto_rawDescOnce.Do(func() {
		file_protos_platform_protoconsts_protoconsts_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_platform_protoconsts_protoconsts_proto_rawDescData)
	})
	return file_protos_platform_protoconsts_protoconsts_proto_rawDescData
}

var file_protos_platform_protoconsts_protoconsts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_platform_protoconsts_protoconsts_proto_goTypes = []interface{}{
	(RefreshType)(0),  // 0: protoconsts.RefreshType
	(ResourceType)(0), // 1: protoconsts.ResourceType
}
var file_protos_platform_protoconsts_protoconsts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_platform_protoconsts_protoconsts_proto_init() }
func file_protos_platform_protoconsts_protoconsts_proto_init() {
	if File_protos_platform_protoconsts_protoconsts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_platform_protoconsts_protoconsts_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_platform_protoconsts_protoconsts_proto_goTypes,
		DependencyIndexes: file_protos_platform_protoconsts_protoconsts_proto_depIdxs,
		EnumInfos:         file_protos_platform_protoconsts_protoconsts_proto_enumTypes,
	}.Build()
	File_protos_platform_protoconsts_protoconsts_proto = out.File
	file_protos_platform_protoconsts_protoconsts_proto_rawDesc = nil
	file_protos_platform_protoconsts_protoconsts_proto_goTypes = nil
	file_protos_platform_protoconsts_protoconsts_proto_depIdxs = nil
}
