import EventEmitter from 'eventemitter3'

export const EE = new EventEmitter()

export enum EE_CUSTOM_EVENT {
  TOGGLE_UPLOAD_DROPDOWN = 'TOGGLE_UPLOAD_DROPDOWN',
  TOGGLE_CLOUDAPP_OPEN = 'TOGGLE_CLOUDAPP_OPEN',
  SHOW_HIDE_FILE = 'SHOW_HIDE_FILE',
  CHANGE_LIST_VIEW = 'CHANGE_LIST_VIEW',
  SERVER_FILE_TO_SUPERCOMPUTING = 'SERVER_FILE_TO_SUPERCOMPUTING',
  SUPERCOMPUTING_TASKKEY = 'SUPERCOMPUTING_TASKKEY',
  SETGRIDLISTSCROLLTOEND = 'SETGRIDLISTSCROLLTOEND'
}
