// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor/monitor.proto

package monitor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueueListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *QueueListRequest) Reset()         { *m = QueueListRequest{} }
func (m *QueueListRequest) String() string { return proto.CompactTextString(m) }
func (*QueueListRequest) ProtoMessage()    {}
func (*QueueListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{0}
}

func (m *QueueListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueListRequest.Unmarshal(m, b)
}
func (m *QueueListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueListRequest.Marshal(b, m, deterministic)
}
func (m *QueueListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueListRequest.Merge(m, src)
}
func (m *QueueListRequest) XXX_Size() int {
	return xxx_messageInfo_QueueListRequest.Size(m)
}
func (m *QueueListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueueListRequest proto.InternalMessageInfo

type GetPlatformCoresRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetPlatformCoresRequest) Reset()         { *m = GetPlatformCoresRequest{} }
func (m *GetPlatformCoresRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlatformCoresRequest) ProtoMessage()    {}
func (*GetPlatformCoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{1}
}

func (m *GetPlatformCoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlatformCoresRequest.Unmarshal(m, b)
}
func (m *GetPlatformCoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlatformCoresRequest.Marshal(b, m, deterministic)
}
func (m *GetPlatformCoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlatformCoresRequest.Merge(m, src)
}
func (m *GetPlatformCoresRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlatformCoresRequest.Size(m)
}
func (m *GetPlatformCoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlatformCoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlatformCoresRequest proto.InternalMessageInfo

type GetPlatformCoresResponse struct {
	PlatformCores        []*PlatformCore `protobuf:"bytes,1,rep,name=platform_cores,json=platformCores,proto3" json:"platform_cores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte          `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32           `json:"-" yaml:"-" xml:"-"`
}

func (m *GetPlatformCoresResponse) Reset()         { *m = GetPlatformCoresResponse{} }
func (m *GetPlatformCoresResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlatformCoresResponse) ProtoMessage()    {}
func (*GetPlatformCoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{2}
}

func (m *GetPlatformCoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlatformCoresResponse.Unmarshal(m, b)
}
func (m *GetPlatformCoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlatformCoresResponse.Marshal(b, m, deterministic)
}
func (m *GetPlatformCoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlatformCoresResponse.Merge(m, src)
}
func (m *GetPlatformCoresResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlatformCoresResponse.Size(m)
}
func (m *GetPlatformCoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlatformCoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlatformCoresResponse proto.InternalMessageInfo

func (m *GetPlatformCoresResponse) GetPlatformCores() []*PlatformCore {
	if m != nil {
		return m.PlatformCores
	}
	return nil
}

type PlatformCore struct {
	PlatformName         string   `protobuf:"bytes,1,opt,name=platform_name,json=platformName,proto3" json:"platform_name,omitempty"`
	TotalCores           int64    `protobuf:"varint,2,opt,name=total_cores,json=totalCores,proto3" json:"total_cores,omitempty"`
	AvailableCores       int64    `protobuf:"varint,3,opt,name=available_cores,json=availableCores,proto3" json:"available_cores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *PlatformCore) Reset()         { *m = PlatformCore{} }
func (m *PlatformCore) String() string { return proto.CompactTextString(m) }
func (*PlatformCore) ProtoMessage()    {}
func (*PlatformCore) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{3}
}

func (m *PlatformCore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformCore.Unmarshal(m, b)
}
func (m *PlatformCore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformCore.Marshal(b, m, deterministic)
}
func (m *PlatformCore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformCore.Merge(m, src)
}
func (m *PlatformCore) XXX_Size() int {
	return xxx_messageInfo_PlatformCore.Size(m)
}
func (m *PlatformCore) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformCore.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformCore proto.InternalMessageInfo

func (m *PlatformCore) GetPlatformName() string {
	if m != nil {
		return m.PlatformName
	}
	return ""
}

func (m *PlatformCore) GetTotalCores() int64 {
	if m != nil {
		return m.TotalCores
	}
	return 0
}

func (m *PlatformCore) GetAvailableCores() int64 {
	if m != nil {
		return m.AvailableCores
	}
	return 0
}

type GetQueueCoreInfosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetQueueCoreInfosRequest) Reset()         { *m = GetQueueCoreInfosRequest{} }
func (m *GetQueueCoreInfosRequest) String() string { return proto.CompactTextString(m) }
func (*GetQueueCoreInfosRequest) ProtoMessage()    {}
func (*GetQueueCoreInfosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{4}
}

func (m *GetQueueCoreInfosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueueCoreInfosRequest.Unmarshal(m, b)
}
func (m *GetQueueCoreInfosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueueCoreInfosRequest.Marshal(b, m, deterministic)
}
func (m *GetQueueCoreInfosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueueCoreInfosRequest.Merge(m, src)
}
func (m *GetQueueCoreInfosRequest) XXX_Size() int {
	return xxx_messageInfo_GetQueueCoreInfosRequest.Size(m)
}
func (m *GetQueueCoreInfosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueueCoreInfosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueueCoreInfosRequest proto.InternalMessageInfo

type GetQueueCoreInfosResponse struct {
	QueueCoreInfos       []*QueueCoreInfo `protobuf:"bytes,1,rep,name=queue_core_infos,json=queueCoreInfos,proto3" json:"queue_core_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte           `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32            `json:"-" yaml:"-" xml:"-"`
}

func (m *GetQueueCoreInfosResponse) Reset()         { *m = GetQueueCoreInfosResponse{} }
func (m *GetQueueCoreInfosResponse) String() string { return proto.CompactTextString(m) }
func (*GetQueueCoreInfosResponse) ProtoMessage()    {}
func (*GetQueueCoreInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{5}
}

func (m *GetQueueCoreInfosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueueCoreInfosResponse.Unmarshal(m, b)
}
func (m *GetQueueCoreInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueueCoreInfosResponse.Marshal(b, m, deterministic)
}
func (m *GetQueueCoreInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueueCoreInfosResponse.Merge(m, src)
}
func (m *GetQueueCoreInfosResponse) XXX_Size() int {
	return xxx_messageInfo_GetQueueCoreInfosResponse.Size(m)
}
func (m *GetQueueCoreInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueueCoreInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueueCoreInfosResponse proto.InternalMessageInfo

func (m *GetQueueCoreInfosResponse) GetQueueCoreInfos() []*QueueCoreInfo {
	if m != nil {
		return m.QueueCoreInfos
	}
	return nil
}

type QueueCoreInfo struct {
	QueueName            string   `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	TotalCores           int64    `protobuf:"varint,2,opt,name=total_cores,json=totalCores,proto3" json:"total_cores,omitempty"`
	AvailableCores       int64    `protobuf:"varint,3,opt,name=available_cores,json=availableCores,proto3" json:"available_cores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *QueueCoreInfo) Reset()         { *m = QueueCoreInfo{} }
func (m *QueueCoreInfo) String() string { return proto.CompactTextString(m) }
func (*QueueCoreInfo) ProtoMessage()    {}
func (*QueueCoreInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{6}
}

func (m *QueueCoreInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueCoreInfo.Unmarshal(m, b)
}
func (m *QueueCoreInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueCoreInfo.Marshal(b, m, deterministic)
}
func (m *QueueCoreInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueCoreInfo.Merge(m, src)
}
func (m *QueueCoreInfo) XXX_Size() int {
	return xxx_messageInfo_QueueCoreInfo.Size(m)
}
func (m *QueueCoreInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueCoreInfo.DiscardUnknown(m)
}

var xxx_messageInfo_QueueCoreInfo proto.InternalMessageInfo

func (m *QueueCoreInfo) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

func (m *QueueCoreInfo) GetTotalCores() int64 {
	if m != nil {
		return m.TotalCores
	}
	return 0
}

func (m *QueueCoreInfo) GetAvailableCores() int64 {
	if m != nil {
		return m.AvailableCores
	}
	return 0
}

type QueueListResponse struct {
	QueueNames           []string `protobuf:"bytes,1,rep,name=queue_names,json=queueNames,proto3" json:"queue_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *QueueListResponse) Reset()         { *m = QueueListResponse{} }
func (m *QueueListResponse) String() string { return proto.CompactTextString(m) }
func (*QueueListResponse) ProtoMessage()    {}
func (*QueueListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{7}
}

func (m *QueueListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueListResponse.Unmarshal(m, b)
}
func (m *QueueListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueListResponse.Marshal(b, m, deterministic)
}
func (m *QueueListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueListResponse.Merge(m, src)
}
func (m *QueueListResponse) XXX_Size() int {
	return xxx_messageInfo_QueueListResponse.Size(m)
}
func (m *QueueListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueListResponse proto.InternalMessageInfo

func (m *QueueListResponse) GetQueueNames() []string {
	if m != nil {
		return m.QueueNames
	}
	return nil
}

type GetQueueAvailableCoresRequest struct {
	QueueNames           []string `protobuf:"bytes,1,rep,name=queue_names,json=queueNames,proto3" json:"queue_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetQueueAvailableCoresRequest) Reset()         { *m = GetQueueAvailableCoresRequest{} }
func (m *GetQueueAvailableCoresRequest) String() string { return proto.CompactTextString(m) }
func (*GetQueueAvailableCoresRequest) ProtoMessage()    {}
func (*GetQueueAvailableCoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{8}
}

func (m *GetQueueAvailableCoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueueAvailableCoresRequest.Unmarshal(m, b)
}
func (m *GetQueueAvailableCoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueueAvailableCoresRequest.Marshal(b, m, deterministic)
}
func (m *GetQueueAvailableCoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueueAvailableCoresRequest.Merge(m, src)
}
func (m *GetQueueAvailableCoresRequest) XXX_Size() int {
	return xxx_messageInfo_GetQueueAvailableCoresRequest.Size(m)
}
func (m *GetQueueAvailableCoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueueAvailableCoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueueAvailableCoresRequest proto.InternalMessageInfo

func (m *GetQueueAvailableCoresRequest) GetQueueNames() []string {
	if m != nil {
		return m.QueueNames
	}
	return nil
}

type GetQueueAvailableCoresResponse struct {
	QueueCores           []*QueueCore `protobuf:"bytes,1,rep,name=queue_cores,json=queueCores,proto3" json:"queue_cores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte       `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32        `json:"-" yaml:"-" xml:"-"`
}

func (m *GetQueueAvailableCoresResponse) Reset()         { *m = GetQueueAvailableCoresResponse{} }
func (m *GetQueueAvailableCoresResponse) String() string { return proto.CompactTextString(m) }
func (*GetQueueAvailableCoresResponse) ProtoMessage()    {}
func (*GetQueueAvailableCoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{9}
}

func (m *GetQueueAvailableCoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueueAvailableCoresResponse.Unmarshal(m, b)
}
func (m *GetQueueAvailableCoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueueAvailableCoresResponse.Marshal(b, m, deterministic)
}
func (m *GetQueueAvailableCoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueueAvailableCoresResponse.Merge(m, src)
}
func (m *GetQueueAvailableCoresResponse) XXX_Size() int {
	return xxx_messageInfo_GetQueueAvailableCoresResponse.Size(m)
}
func (m *GetQueueAvailableCoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueueAvailableCoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueueAvailableCoresResponse proto.InternalMessageInfo

func (m *GetQueueAvailableCoresResponse) GetQueueCores() []*QueueCore {
	if m != nil {
		return m.QueueCores
	}
	return nil
}

type QueueCore struct {
	QueueName            string   `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	CoreNum              int64    `protobuf:"varint,2,opt,name=core_num,json=coreNum,proto3" json:"core_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *QueueCore) Reset()         { *m = QueueCore{} }
func (m *QueueCore) String() string { return proto.CompactTextString(m) }
func (*QueueCore) ProtoMessage()    {}
func (*QueueCore) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{10}
}

func (m *QueueCore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueCore.Unmarshal(m, b)
}
func (m *QueueCore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueCore.Marshal(b, m, deterministic)
}
func (m *QueueCore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueCore.Merge(m, src)
}
func (m *QueueCore) XXX_Size() int {
	return xxx_messageInfo_QueueCore.Size(m)
}
func (m *QueueCore) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueCore.DiscardUnknown(m)
}

var xxx_messageInfo_QueueCore proto.InternalMessageInfo

func (m *QueueCore) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

func (m *QueueCore) GetCoreNum() int64 {
	if m != nil {
		return m.CoreNum
	}
	return 0
}

func init() {
	proto.RegisterType((*QueueListRequest)(nil), "monitor.QueueListRequest")
	proto.RegisterType((*GetPlatformCoresRequest)(nil), "monitor.GetPlatformCoresRequest")
	proto.RegisterType((*GetPlatformCoresResponse)(nil), "monitor.GetPlatformCoresResponse")
	proto.RegisterType((*PlatformCore)(nil), "monitor.PlatformCore")
	proto.RegisterType((*GetQueueCoreInfosRequest)(nil), "monitor.GetQueueCoreInfosRequest")
	proto.RegisterType((*GetQueueCoreInfosResponse)(nil), "monitor.GetQueueCoreInfosResponse")
	proto.RegisterType((*QueueCoreInfo)(nil), "monitor.QueueCoreInfo")
	proto.RegisterType((*QueueListResponse)(nil), "monitor.QueueListResponse")
	proto.RegisterType((*GetQueueAvailableCoresRequest)(nil), "monitor.GetQueueAvailableCoresRequest")
	proto.RegisterType((*GetQueueAvailableCoresResponse)(nil), "monitor.GetQueueAvailableCoresResponse")
	proto.RegisterType((*QueueCore)(nil), "monitor.QueueCore")
}

func init() { proto.RegisterFile("monitor/monitor.proto", fileDescriptor_94d5950496a7550d) }

var fileDescriptor_94d5950496a7550d = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x25, 0x5b, 0xb0, 0xe6, 0x76, 0xb7, 0x76, 0x07, 0x76, 0x6d, 0x02, 0xeb, 0x66, 0x23, 0xb8,
	0x7d, 0xb1, 0x81, 0x5d, 0x1f, 0x7d, 0x58, 0x57, 0x44, 0x04, 0x5d, 0x34, 0x20, 0xca, 0x82, 0x94,
	0x69, 0x99, 0x42, 0x20, 0x33, 0x93, 0x66, 0x26, 0xa2, 0x0f, 0x7e, 0xb2, 0xff, 0x20, 0x99, 0xdc,
	0xc4, 0x49, 0x13, 0xdb, 0x17, 0x9f, 0xca, 0xdc, 0x73, 0xef, 0x39, 0x39, 0x67, 0x7a, 0x07, 0x4e,
	0xb8, 0x14, 0x89, 0x96, 0x79, 0x84, 0xbf, 0xf3, 0x2c, 0x97, 0x5a, 0x92, 0x21, 0x1e, 0x43, 0x02,
	0x93, 0x4f, 0x05, 0x2b, 0xd8, 0xfb, 0x44, 0xe9, 0x98, 0x6d, 0x0a, 0xa6, 0x74, 0xe8, 0xc1, 0xe3,
	0xb7, 0x4c, 0x7f, 0x4c, 0xa9, 0x5e, 0xcb, 0x9c, 0xbf, 0x96, 0x39, 0x53, 0x35, 0xf4, 0x15, 0xa6,
	0x5d, 0x48, 0x65, 0x52, 0x28, 0x46, 0x5e, 0xc2, 0x38, 0x43, 0x60, 0xb1, 0x2a, 0x91, 0xa9, 0x13,
	0x0c, 0x66, 0xa3, 0xab, 0x93, 0x79, 0xad, 0x6d, 0xcf, 0xc5, 0x47, 0x99, 0xcd, 0x12, 0xfe, 0x82,
	0x43, 0x1b, 0x26, 0x4f, 0xa1, 0x69, 0x58, 0x08, 0xca, 0xd9, 0xd4, 0x09, 0x9c, 0x99, 0x1b, 0x1f,
	0xd6, 0xc5, 0x3b, 0xca, 0x19, 0x39, 0x87, 0x91, 0x96, 0x9a, 0xa6, 0xa8, 0x77, 0x10, 0x38, 0xb3,
	0x41, 0x0c, 0xa6, 0x64, 0x58, 0xc9, 0x25, 0x3c, 0xa2, 0xdf, 0x69, 0x92, 0xd2, 0x65, 0xca, 0xb0,
	0x69, 0x60, 0x9a, 0xc6, 0x4d, 0xb9, 0x92, 0xf7, 0x8d, 0x31, 0x13, 0x45, 0x59, 0x78, 0x27, 0xd6,
	0xb2, 0x31, 0xfd, 0x0d, 0xbc, 0x1e, 0x0c, 0x5d, 0xdf, 0xc0, 0x64, 0x53, 0x22, 0x86, 0x7d, 0x91,
	0x94, 0x18, 0xfa, 0x3e, 0x6d, 0x7c, 0xb7, 0x46, 0xe3, 0xf1, 0xa6, 0xc5, 0x14, 0xfe, 0x80, 0xa3,
	0x56, 0x03, 0x39, 0x03, 0xa8, 0x28, 0x2d, 0xdf, 0xae, 0xa9, 0xfc, 0x67, 0xd3, 0x2f, 0xe0, 0xd8,
	0xba, 0x7c, 0x34, 0x74, 0x0e, 0xa3, 0xbf, 0xea, 0x95, 0x17, 0x37, 0x86, 0x46, 0x5e, 0x85, 0x37,
	0x70, 0x56, 0xc7, 0xf1, 0xaa, 0xc5, 0x87, 0x79, 0xed, 0x67, 0xf8, 0x0c, 0x4f, 0xfe, 0xc5, 0x80,
	0x1f, 0x71, 0x5d, 0x53, 0xd8, 0x7f, 0x24, 0xd2, 0x0d, 0x14, 0x69, 0x2b, 0x3b, 0x6f, 0xc0, 0x6d,
	0x80, 0x7d, 0x21, 0x7a, 0xf0, 0xd0, 0x5c, 0x98, 0x28, 0x38, 0x26, 0x38, 0x2c, 0xcf, 0x77, 0x05,
	0xbf, 0xfa, 0x7d, 0x00, 0xc3, 0x0f, 0x95, 0x10, 0xb9, 0x45, 0xca, 0x32, 0x21, 0xe2, 0xb5, 0xf5,
	0xad, 0x95, 0xf1, 0xfd, 0x3e, 0x08, 0xbd, 0x24, 0x70, 0xda, 0xef, 0x96, 0x3c, 0x6b, 0xa6, 0x76,
	0x06, 0xea, 0x5f, 0xee, 0xed, 0x43, 0xa9, 0x2f, 0x30, 0xd9, 0x5e, 0x4f, 0x12, 0xd8, 0xc3, 0x7d,
	0x4b, 0xed, 0x5f, 0xec, 0xe8, 0x40, 0xe2, 0x7b, 0x38, 0xee, 0xac, 0x00, 0xb9, 0xe8, 0x7c, 0xd6,
	0xf6, 0xea, 0xf8, 0xe1, 0xae, 0x96, 0x8a, 0xfb, 0x36, 0xba, 0x7f, 0xfe, 0xb3, 0xa0, 0x42, 0x15,
	0x54, 0xcc, 0x57, 0x22, 0xca, 0x54, 0x16, 0x25, 0x42, 0xb3, 0x5c, 0xd0, 0x34, 0x5a, 0x49, 0xce,
	0xa5, 0x88, 0xcc, 0xa3, 0x55, 0x3f, 0x61, 0xcb, 0x07, 0xe6, 0x78, 0xfd, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x31, 0xf3, 0xa8, 0x20, 0xdc, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorClient interface {
	// QueueList 获取队列列表
	QueueList(ctx context.Context, in *QueueListRequest, opts ...grpc.CallOption) (*QueueListResponse, error)
	// GetQueueAvailableCores 获取队列及对应的可用核数
	GetQueueAvailableCores(ctx context.Context, in *GetQueueAvailableCoresRequest, opts ...grpc.CallOption) (*GetQueueAvailableCoresResponse, error)
	// GetPlatformCores 获取Platform及对应核数
	GetPlatformCores(ctx context.Context, in *GetPlatformCoresRequest, opts ...grpc.CallOption) (*GetPlatformCoresResponse, error)
	// GetQueueCoreInfos 获取Queue及对应核数
	GetQueueCoreInfos(ctx context.Context, in *GetQueueCoreInfosRequest, opts ...grpc.CallOption) (*GetQueueCoreInfosResponse, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) QueueList(ctx context.Context, in *QueueListRequest, opts ...grpc.CallOption) (*QueueListResponse, error) {
	out := new(QueueListResponse)
	err := c.cc.Invoke(ctx, "/monitor.Monitor/QueueList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) GetQueueAvailableCores(ctx context.Context, in *GetQueueAvailableCoresRequest, opts ...grpc.CallOption) (*GetQueueAvailableCoresResponse, error) {
	out := new(GetQueueAvailableCoresResponse)
	err := c.cc.Invoke(ctx, "/monitor.Monitor/GetQueueAvailableCores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) GetPlatformCores(ctx context.Context, in *GetPlatformCoresRequest, opts ...grpc.CallOption) (*GetPlatformCoresResponse, error) {
	out := new(GetPlatformCoresResponse)
	err := c.cc.Invoke(ctx, "/monitor.Monitor/GetPlatformCores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) GetQueueCoreInfos(ctx context.Context, in *GetQueueCoreInfosRequest, opts ...grpc.CallOption) (*GetQueueCoreInfosResponse, error) {
	out := new(GetQueueCoreInfosResponse)
	err := c.cc.Invoke(ctx, "/monitor.Monitor/GetQueueCoreInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
type MonitorServer interface {
	// QueueList 获取队列列表
	QueueList(context.Context, *QueueListRequest) (*QueueListResponse, error)
	// GetQueueAvailableCores 获取队列及对应的可用核数
	GetQueueAvailableCores(context.Context, *GetQueueAvailableCoresRequest) (*GetQueueAvailableCoresResponse, error)
	// GetPlatformCores 获取Platform及对应核数
	GetPlatformCores(context.Context, *GetPlatformCoresRequest) (*GetPlatformCoresResponse, error)
	// GetQueueCoreInfos 获取Queue及对应核数
	GetQueueCoreInfos(context.Context, *GetQueueCoreInfosRequest) (*GetQueueCoreInfosResponse, error)
}

// UnimplementedMonitorServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorServer struct {
}

func (*UnimplementedMonitorServer) QueueList(ctx context.Context, req *QueueListRequest) (*QueueListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueList not implemented")
}
func (*UnimplementedMonitorServer) GetQueueAvailableCores(ctx context.Context, req *GetQueueAvailableCoresRequest) (*GetQueueAvailableCoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueAvailableCores not implemented")
}
func (*UnimplementedMonitorServer) GetPlatformCores(ctx context.Context, req *GetPlatformCoresRequest) (*GetPlatformCoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlatformCores not implemented")
}
func (*UnimplementedMonitorServer) GetQueueCoreInfos(ctx context.Context, req *GetQueueCoreInfosRequest) (*GetQueueCoreInfosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueCoreInfos not implemented")
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_QueueList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).QueueList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Monitor/QueueList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).QueueList(ctx, req.(*QueueListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_GetQueueAvailableCores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueAvailableCoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).GetQueueAvailableCores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Monitor/GetQueueAvailableCores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).GetQueueAvailableCores(ctx, req.(*GetQueueAvailableCoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_GetPlatformCores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformCoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).GetPlatformCores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Monitor/GetPlatformCores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).GetPlatformCores(ctx, req.(*GetPlatformCoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_GetQueueCoreInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueCoreInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).GetQueueCoreInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Monitor/GetQueueCoreInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).GetQueueCoreInfos(ctx, req.(*GetQueueCoreInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueList",
			Handler:    _Monitor_QueueList_Handler,
		},
		{
			MethodName: "GetQueueAvailableCores",
			Handler:    _Monitor_GetQueueAvailableCores_Handler,
		},
		{
			MethodName: "GetPlatformCores",
			Handler:    _Monitor_GetPlatformCores_Handler,
		},
		{
			MethodName: "GetQueueCoreInfos",
			Handler:    _Monitor_GetQueueCoreInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor/monitor.proto",
}
