// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/job/residual.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Residual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vars          []*ResidualVar `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty"`
	AvailableXvar []string       `protobuf:"bytes,2,rep,name=available_xvar,json=availableXvar,proto3" json:"available_xvar,omitempty"`
}

func (x *Residual) Reset() {
	*x = Residual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_residual_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Residual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Residual) ProtoMessage() {}

func (x *Residual) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_residual_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Residual.ProtoReflect.Descriptor instead.
func (*Residual) Descriptor() ([]byte, []int) {
	return file_proto_job_residual_proto_rawDescGZIP(), []int{0}
}

func (x *Residual) GetVars() []*ResidualVar {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *Residual) GetAvailableXvar() []string {
	if x != nil {
		return x.AvailableXvar
	}
	return nil
}

type ResidualVar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Name   string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ResidualVar) Reset() {
	*x = ResidualVar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_residual_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResidualVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResidualVar) ProtoMessage() {}

func (x *ResidualVar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_residual_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResidualVar.ProtoReflect.Descriptor instead.
func (*ResidualVar) Descriptor() ([]byte, []int) {
	return file_proto_job_residual_proto_rawDescGZIP(), []int{1}
}

func (x *ResidualVar) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ResidualVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetResidualRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: `validate:"is_ysid,required"`
	JobRuntimeId string `protobuf:"bytes,1,opt,name=job_runtime_id,json=jobRuntimeId,proto3" json:"job_runtime_id,omitempty"`
	// @inject_tag: `validate:"required"`
	Residual *Residual `protobuf:"bytes,2,opt,name=residual,proto3" json:"residual,omitempty"`
}

func (x *SetResidualRequest) Reset() {
	*x = SetResidualRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_residual_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResidualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResidualRequest) ProtoMessage() {}

func (x *SetResidualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_residual_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResidualRequest.ProtoReflect.Descriptor instead.
func (*SetResidualRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_residual_proto_rawDescGZIP(), []int{2}
}

func (x *SetResidualRequest) GetJobRuntimeId() string {
	if x != nil {
		return x.JobRuntimeId
	}
	return ""
}

func (x *SetResidualRequest) GetResidual() *Residual {
	if x != nil {
		return x.Residual
	}
	return nil
}

type GetResidualRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: `validate:"is_ysid,required"`
	JobRuntimeId string `protobuf:"bytes,1,opt,name=job_runtime_id,json=jobRuntimeId,proto3" json:"job_runtime_id,omitempty"`
}

func (x *GetResidualRequest) Reset() {
	*x = GetResidualRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_residual_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResidualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResidualRequest) ProtoMessage() {}

func (x *GetResidualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_residual_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResidualRequest.ProtoReflect.Descriptor instead.
func (*GetResidualRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_residual_proto_rawDescGZIP(), []int{3}
}

func (x *GetResidualRequest) GetJobRuntimeId() string {
	if x != nil {
		return x.JobRuntimeId
	}
	return ""
}

type GetResidualReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Residual *Residual `protobuf:"bytes,2,opt,name=residual,proto3" json:"residual,omitempty"`
}

func (x *GetResidualReply) Reset() {
	*x = GetResidualReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_residual_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResidualReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResidualReply) ProtoMessage() {}

func (x *GetResidualReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_residual_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResidualReply.ProtoReflect.Descriptor instead.
func (*GetResidualReply) Descriptor() ([]byte, []int) {
	return file_proto_job_residual_proto_rawDescGZIP(), []int{4}
}

func (x *GetResidualReply) GetResidual() *Residual {
	if x != nil {
		return x.Residual
	}
	return nil
}

var File_proto_job_residual_proto protoreflect.FileDescriptor

var file_proto_job_residual_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x69,
	0x64, 0x75, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6a, 0x6f, 0x62, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x69, 0x64, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x72, 0x52, 0x04, 0x76, 0x61, 0x72, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x78, 0x76, 0x61, 0x72,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x58, 0x76, 0x61, 0x72, 0x22, 0x39, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x69, 0x64, 0x75, 0x61,
	0x6c, 0x56, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x65, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x6a, 0x6f, 0x62, 0x5f, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x22, 0x3a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0e, 0x6a, 0x6f, 0x62, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x69, 0x64, 0x75,
	0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x69, 0x64,
	0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6a, 0x6f, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x52, 0x08, 0x72, 0x65, 0x73, 0x69, 0x64, 0x75,
	0x61, 0x6c, 0x32, 0x92, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x69, 0x64,
	0x75, 0x61, 0x6c, 0x12, 0x17, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x69, 0x64, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x69, 0x64, 0x75, 0x61, 0x6c, 0x12, 0x17, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x69, 0x64, 0x75, 0x61, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x2e, 0x79,
	0x75, 0x61, 0x6e, 0x73, 0x75, 0x61, 0x6e, 0x2e, 0x63, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2d, 0x72, 0x6f, 0x6f, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6a, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_job_residual_proto_rawDescOnce sync.Once
	file_proto_job_residual_proto_rawDescData = file_proto_job_residual_proto_rawDesc
)

func file_proto_job_residual_proto_rawDescGZIP() []byte {
	file_proto_job_residual_proto_rawDescOnce.Do(func() {
		file_proto_job_residual_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_job_residual_proto_rawDescData)
	})
	return file_proto_job_residual_proto_rawDescData
}

var file_proto_job_residual_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_job_residual_proto_goTypes = []interface{}{
	(*Residual)(nil),           // 0: job.Residual
	(*ResidualVar)(nil),        // 1: job.ResidualVar
	(*SetResidualRequest)(nil), // 2: job.SetResidualRequest
	(*GetResidualRequest)(nil), // 3: job.GetResidualRequest
	(*GetResidualReply)(nil),   // 4: job.GetResidualReply
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_proto_job_residual_proto_depIdxs = []int32{
	1, // 0: job.Residual.vars:type_name -> job.ResidualVar
	0, // 1: job.SetResidualRequest.residual:type_name -> job.Residual
	0, // 2: job.GetResidualReply.residual:type_name -> job.Residual
	2, // 3: job.ResidualStore.SetResidual:input_type -> job.SetResidualRequest
	3, // 4: job.ResidualStore.GetResidual:input_type -> job.GetResidualRequest
	5, // 5: job.ResidualStore.SetResidual:output_type -> google.protobuf.Empty
	4, // 6: job.ResidualStore.GetResidual:output_type -> job.GetResidualReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_job_residual_proto_init() }
func file_proto_job_residual_proto_init() {
	if File_proto_job_residual_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_job_residual_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Residual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_residual_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResidualVar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_residual_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResidualRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_residual_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResidualRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_residual_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResidualReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_job_residual_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_job_residual_proto_goTypes,
		DependencyIndexes: file_proto_job_residual_proto_depIdxs,
		MessageInfos:      file_proto_job_residual_proto_msgTypes,
	}.Build()
	File_proto_job_residual_proto = out.File
	file_proto_job_residual_proto_rawDesc = nil
	file_proto_job_residual_proto_goTypes = nil
	file_proto_job_residual_proto_depIdxs = nil
}
