// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/job/sc.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 资源类型
type ResourceType int32

const (
	ResourceType_UNKNOWN ResourceType = 0
	// 可用节点数
	ResourceType_NODE ResourceType = 1
	// 可用核数
	ResourceType_CORES ResourceType = 2
	// 可用作业数
	ResourceType_TASK ResourceType = 3
	// 可用作业数
	ResourceType_APP_LIC ResourceType = 4
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NODE",
		2: "CORES",
		3: "TASK",
		4: "APP_LIC",
	}
	ResourceType_value = map[string]int32{
		"UNKNOWN": 0,
		"NODE":    1,
		"CORES":   2,
		"TASK":    3,
		"APP_LIC": 4,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_job_sc_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_proto_job_sc_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_job_sc_proto_rawDescGZIP(), []int{0}
}

type AddSCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScId     string `protobuf:"bytes,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
	ScName   string `protobuf:"bytes,2,opt,name=sc_name,json=scName,proto3" json:"sc_name,omitempty"`
	TierName string `protobuf:"bytes,3,opt,name=tier_name,json=tierName,proto3" json:"tier_name,omitempty"`
}

func (x *AddSCRequest) Reset() {
	*x = AddSCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_sc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSCRequest) ProtoMessage() {}

func (x *AddSCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_sc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSCRequest.ProtoReflect.Descriptor instead.
func (*AddSCRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_sc_proto_rawDescGZIP(), []int{0}
}

func (x *AddSCRequest) GetScId() string {
	if x != nil {
		return x.ScId
	}
	return ""
}

func (x *AddSCRequest) GetScName() string {
	if x != nil {
		return x.ScName
	}
	return ""
}

func (x *AddSCRequest) GetTierName() string {
	if x != nil {
		return x.TierName
	}
	return ""
}

type UpdateSCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScId     string `protobuf:"bytes,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
	ScName   string `protobuf:"bytes,2,opt,name=sc_name,json=scName,proto3" json:"sc_name,omitempty"`
	TierName string `protobuf:"bytes,3,opt,name=tier_name,json=tierName,proto3" json:"tier_name,omitempty"`
}

func (x *UpdateSCRequest) Reset() {
	*x = UpdateSCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_sc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSCRequest) ProtoMessage() {}

func (x *UpdateSCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_sc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSCRequest.ProtoReflect.Descriptor instead.
func (*UpdateSCRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_sc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSCRequest) GetScId() string {
	if x != nil {
		return x.ScId
	}
	return ""
}

func (x *UpdateSCRequest) GetScName() string {
	if x != nil {
		return x.ScName
	}
	return ""
}

func (x *UpdateSCRequest) GetTierName() string {
	if x != nil {
		return x.TierName
	}
	return ""
}

type DeleteSCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScId string `protobuf:"bytes,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
}

func (x *DeleteSCRequest) Reset() {
	*x = DeleteSCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_sc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSCRequest) ProtoMessage() {}

func (x *DeleteSCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_sc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSCRequest.ProtoReflect.Descriptor instead.
func (*DeleteSCRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_sc_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSCRequest) GetScId() string {
	if x != nil {
		return x.ScId
	}
	return ""
}

type GetSCAvailableResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 超算id
	// @inject_tag: `validate:"required"`
	ScId string `protobuf:"bytes,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
	// 软件
	AppType string `protobuf:"bytes,2,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	// 资源类型
	// @inject_tag: `validate:"required"`
	ResourceType ResourceType `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3,enum=job.ResourceType" json:"resource_type,omitempty"`
}

func (x *GetSCAvailableResourceRequest) Reset() {
	*x = GetSCAvailableResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_sc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSCAvailableResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSCAvailableResourceRequest) ProtoMessage() {}

func (x *GetSCAvailableResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_sc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSCAvailableResourceRequest.ProtoReflect.Descriptor instead.
func (*GetSCAvailableResourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_sc_proto_rawDescGZIP(), []int{3}
}

func (x *GetSCAvailableResourceRequest) GetScId() string {
	if x != nil {
		return x.ScId
	}
	return ""
}

func (x *GetSCAvailableResourceRequest) GetAppType() string {
	if x != nil {
		return x.AppType
	}
	return ""
}

func (x *GetSCAvailableResourceRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_UNKNOWN
}

type GetSCAvailableResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 可用资源计数
	AvailableCount int64 `protobuf:"varint,1,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"`
	// 是否成功获取
	IsSuccess bool `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
}

func (x *GetSCAvailableResourceResponse) Reset() {
	*x = GetSCAvailableResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_sc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSCAvailableResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSCAvailableResourceResponse) ProtoMessage() {}

func (x *GetSCAvailableResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_sc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSCAvailableResourceResponse.ProtoReflect.Descriptor instead.
func (*GetSCAvailableResourceResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_sc_proto_rawDescGZIP(), []int{4}
}

func (x *GetSCAvailableResourceResponse) GetAvailableCount() int64 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

func (x *GetSCAvailableResourceResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type ZoneSCInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Zone string `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	ScId string `protobuf:"bytes,2,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
}

func (x *ZoneSCInfo) Reset() {
	*x = ZoneSCInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_sc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZoneSCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneSCInfo) ProtoMessage() {}

func (x *ZoneSCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_sc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneSCInfo.ProtoReflect.Descriptor instead.
func (*ZoneSCInfo) Descriptor() ([]byte, []int) {
	return file_proto_job_sc_proto_rawDescGZIP(), []int{5}
}

func (x *ZoneSCInfo) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ZoneSCInfo) GetScId() string {
	if x != nil {
		return x.ScId
	}
	return ""
}

type GetZoneSCListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Zones []*ZoneSCInfo `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
}

func (x *GetZoneSCListResponse) Reset() {
	*x = GetZoneSCListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_job_sc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetZoneSCListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneSCListResponse) ProtoMessage() {}

func (x *GetZoneSCListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_sc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneSCListResponse.ProtoReflect.Descriptor instead.
func (*GetZoneSCListResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_sc_proto_rawDescGZIP(), []int{6}
}

func (x *GetZoneSCListResponse) GetZones() []*ZoneSCInfo {
	if x != nil {
		return x.Zones
	}
	return nil
}

var File_proto_job_sc_proto protoreflect.FileDescriptor

var file_proto_job_sc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x73, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6a, 0x6f, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x53, 0x43, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x63, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x5c, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x43, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x63, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x63, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x26, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x63, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x53,
	0x43, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x63, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x68, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x53, 0x43, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x0a, 0x5a,
	0x6f, 0x6e, 0x65, 0x53, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x13, 0x0a,
	0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x63,
	0x49, 0x64, 0x22, 0x3e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x43, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x7a,
	0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x7a, 0x6f, 0x6e,
	0x65, 0x73, 0x2a, 0x47, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4f, 0x52,
	0x45, 0x53, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x41, 0x53, 0x4b, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x41, 0x50, 0x50, 0x5f, 0x4c, 0x49, 0x43, 0x10, 0x04, 0x32, 0xde, 0x02, 0x0a, 0x02,
	0x53, 0x43, 0x12, 0x34, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x53, 0x43, 0x12, 0x11, 0x2e, 0x6a, 0x6f,
	0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x43, 0x12, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x43,
	0x12, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x43, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x63, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x43, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x43, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x43, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x5a, 0x6f, 0x6e, 0x65,
	0x53, 0x43, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x43, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x2e, 0x79, 0x75, 0x61, 0x6e, 0x73, 0x75, 0x61, 0x6e, 0x2e, 0x63, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x72, 0x6f, 0x6f, 0x74, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_job_sc_proto_rawDescOnce sync.Once
	file_proto_job_sc_proto_rawDescData = file_proto_job_sc_proto_rawDesc
)

func file_proto_job_sc_proto_rawDescGZIP() []byte {
	file_proto_job_sc_proto_rawDescOnce.Do(func() {
		file_proto_job_sc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_job_sc_proto_rawDescData)
	})
	return file_proto_job_sc_proto_rawDescData
}

var file_proto_job_sc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_job_sc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_job_sc_proto_goTypes = []interface{}{
	(ResourceType)(0),                      // 0: job.ResourceType
	(*AddSCRequest)(nil),                   // 1: job.AddSCRequest
	(*UpdateSCRequest)(nil),                // 2: job.UpdateSCRequest
	(*DeleteSCRequest)(nil),                // 3: job.DeleteSCRequest
	(*GetSCAvailableResourceRequest)(nil),  // 4: job.GetSCAvailableResourceRequest
	(*GetSCAvailableResourceResponse)(nil), // 5: job.GetSCAvailableResourceResponse
	(*ZoneSCInfo)(nil),                     // 6: job.ZoneSCInfo
	(*GetZoneSCListResponse)(nil),          // 7: job.GetZoneSCListResponse
	(*emptypb.Empty)(nil),                  // 8: google.protobuf.Empty
}
var file_proto_job_sc_proto_depIdxs = []int32{
	0, // 0: job.GetSCAvailableResourceRequest.resource_type:type_name -> job.ResourceType
	6, // 1: job.GetZoneSCListResponse.zones:type_name -> job.ZoneSCInfo
	1, // 2: job.SC.AddSC:input_type -> job.AddSCRequest
	2, // 3: job.SC.UpdateSC:input_type -> job.UpdateSCRequest
	3, // 4: job.SC.DeleteSC:input_type -> job.DeleteSCRequest
	4, // 5: job.SC.GetSCAvailableResource:input_type -> job.GetSCAvailableResourceRequest
	8, // 6: job.SC.GetZoneSCList:input_type -> google.protobuf.Empty
	8, // 7: job.SC.AddSC:output_type -> google.protobuf.Empty
	8, // 8: job.SC.UpdateSC:output_type -> google.protobuf.Empty
	8, // 9: job.SC.DeleteSC:output_type -> google.protobuf.Empty
	5, // 10: job.SC.GetSCAvailableResource:output_type -> job.GetSCAvailableResourceResponse
	7, // 11: job.SC.GetZoneSCList:output_type -> job.GetZoneSCListResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_job_sc_proto_init() }
func file_proto_job_sc_proto_init() {
	if File_proto_job_sc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_job_sc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_sc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_sc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_sc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSCAvailableResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_sc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSCAvailableResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_sc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZoneSCInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_job_sc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetZoneSCListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_job_sc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_job_sc_proto_goTypes,
		DependencyIndexes: file_proto_job_sc_proto_depIdxs,
		EnumInfos:         file_proto_job_sc_proto_enumTypes,
		MessageInfos:      file_proto_job_sc_proto_msgTypes,
	}.Build()
	File_proto_job_sc_proto = out.File
	file_proto_job_sc_proto_rawDesc = nil
	file_proto_job_sc_proto_goTypes = nil
	file_proto_job_sc_proto_depIdxs = nil
}
