CREATE TABLE `sso_user` (
    `ysid` bigint NOT NULL,
    `name` varchar(128) NOT NULL,
    `real_name` varchar(128) NOT NULL,
    `pwd_hash` varchar(128) DEFAULT NULL,
    `email` varchar(128) DEFAULT NULL,
    `phone` varchar(16) DEFAULT NULL,
    `wechat_union_id` varchar(28) DEFAULT NULL,
    `wechat_open_id` varchar(128) NOT NULL,
    `wechat_nick_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    `headimg_url` text COMMENT '用户头像',
    `user_channel` varchar(128) DEFAULT '' COMMENT '用户渠道，eg:官网注册/微信/微博/抖音/知乎...',
    `user_source` varchar(200) NOT NULL DEFAULT '官网注册' COMMENT '用户来源，eg:xxx活动注册/xxx用户推荐',
    `user_referer` bigint DEFAULT NULL COMMENT '用户推荐人，保留字段，判断用户推荐关系及营销价值',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `is_activated` tinyint(1) DEFAULT '1',
    `idm_id` varchar(28) NOT NULL DEFAULT '' COMMENT 'idm id',
    `company` varchar(255) NOT NULL DEFAULT '' COMMENT '所属公司',
    PRIMARY KEY (`ysid`),
    UNIQUE KEY `email` (`email`),
    UNIQUE KEY `phone` (`phone`),
    UNIQUE KEY `wechat_union_id` (`wechat_union_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3