// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sysconfig/sysconfig.proto

package sysconfig

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetJobConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetJobConfigRequest) Reset()         { *m = GetJobConfigRequest{} }
func (m *GetJobConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobConfigRequest) ProtoMessage()    {}
func (*GetJobConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{0}
}

func (m *GetJobConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobConfigRequest.Unmarshal(m, b)
}
func (m *GetJobConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetJobConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobConfigRequest.Merge(m, src)
}
func (m *GetJobConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobConfigRequest.Size(m)
}
func (m *GetJobConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobConfigRequest proto.InternalMessageInfo

type GetJobConfigResponse struct {
	Queue                string   `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetJobConfigResponse) Reset()         { *m = GetJobConfigResponse{} }
func (m *GetJobConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobConfigResponse) ProtoMessage()    {}
func (*GetJobConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{1}
}

func (m *GetJobConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobConfigResponse.Unmarshal(m, b)
}
func (m *GetJobConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetJobConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobConfigResponse.Merge(m, src)
}
func (m *GetJobConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobConfigResponse.Size(m)
}
func (m *GetJobConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobConfigResponse proto.InternalMessageInfo

func (m *GetJobConfigResponse) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

type SetJobConfigRequest struct {
	Queue                string   `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *SetJobConfigRequest) Reset()         { *m = SetJobConfigRequest{} }
func (m *SetJobConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetJobConfigRequest) ProtoMessage()    {}
func (*SetJobConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{2}
}

func (m *SetJobConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetJobConfigRequest.Unmarshal(m, b)
}
func (m *SetJobConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetJobConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetJobConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetJobConfigRequest.Merge(m, src)
}
func (m *SetJobConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetJobConfigRequest.Size(m)
}
func (m *SetJobConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetJobConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetJobConfigRequest proto.InternalMessageInfo

func (m *SetJobConfigRequest) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

type SetJobConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *SetJobConfigResponse) Reset()         { *m = SetJobConfigResponse{} }
func (m *SetJobConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetJobConfigResponse) ProtoMessage()    {}
func (*SetJobConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{3}
}

func (m *SetJobConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetJobConfigResponse.Unmarshal(m, b)
}
func (m *SetJobConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetJobConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetJobConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetJobConfigResponse.Merge(m, src)
}
func (m *SetJobConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetJobConfigResponse.Size(m)
}
func (m *SetJobConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetJobConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetJobConfigResponse proto.InternalMessageInfo

type GetJobBurstConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetJobBurstConfigRequest) Reset()         { *m = GetJobBurstConfigRequest{} }
func (m *GetJobBurstConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobBurstConfigRequest) ProtoMessage()    {}
func (*GetJobBurstConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{4}
}

func (m *GetJobBurstConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobBurstConfigRequest.Unmarshal(m, b)
}
func (m *GetJobBurstConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobBurstConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetJobBurstConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobBurstConfigRequest.Merge(m, src)
}
func (m *GetJobBurstConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobBurstConfigRequest.Size(m)
}
func (m *GetJobBurstConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobBurstConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobBurstConfigRequest proto.InternalMessageInfo

type GetJobBurstConfigResponse struct {
	Enable               bool     `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Threshold            int64    `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetJobBurstConfigResponse) Reset()         { *m = GetJobBurstConfigResponse{} }
func (m *GetJobBurstConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobBurstConfigResponse) ProtoMessage()    {}
func (*GetJobBurstConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{5}
}

func (m *GetJobBurstConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobBurstConfigResponse.Unmarshal(m, b)
}
func (m *GetJobBurstConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobBurstConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetJobBurstConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobBurstConfigResponse.Merge(m, src)
}
func (m *GetJobBurstConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobBurstConfigResponse.Size(m)
}
func (m *GetJobBurstConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobBurstConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobBurstConfigResponse proto.InternalMessageInfo

func (m *GetJobBurstConfigResponse) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *GetJobBurstConfigResponse) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type SetJobBurstConfigRequest struct {
	Enable               bool     `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Threshold            int64    `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *SetJobBurstConfigRequest) Reset()         { *m = SetJobBurstConfigRequest{} }
func (m *SetJobBurstConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetJobBurstConfigRequest) ProtoMessage()    {}
func (*SetJobBurstConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{6}
}

func (m *SetJobBurstConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetJobBurstConfigRequest.Unmarshal(m, b)
}
func (m *SetJobBurstConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetJobBurstConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetJobBurstConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetJobBurstConfigRequest.Merge(m, src)
}
func (m *SetJobBurstConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetJobBurstConfigRequest.Size(m)
}
func (m *SetJobBurstConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetJobBurstConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetJobBurstConfigRequest proto.InternalMessageInfo

func (m *SetJobBurstConfigRequest) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *SetJobBurstConfigRequest) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type SetJobBurstConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *SetJobBurstConfigResponse) Reset()         { *m = SetJobBurstConfigResponse{} }
func (m *SetJobBurstConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetJobBurstConfigResponse) ProtoMessage()    {}
func (*SetJobBurstConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{7}
}

func (m *SetJobBurstConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetJobBurstConfigResponse.Unmarshal(m, b)
}
func (m *SetJobBurstConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetJobBurstConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetJobBurstConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetJobBurstConfigResponse.Merge(m, src)
}
func (m *SetJobBurstConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetJobBurstConfigResponse.Size(m)
}
func (m *SetJobBurstConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetJobBurstConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetJobBurstConfigResponse proto.InternalMessageInfo

type GetRBACDefaultRoleIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetRBACDefaultRoleIdRequest) Reset()         { *m = GetRBACDefaultRoleIdRequest{} }
func (m *GetRBACDefaultRoleIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetRBACDefaultRoleIdRequest) ProtoMessage()    {}
func (*GetRBACDefaultRoleIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{8}
}

func (m *GetRBACDefaultRoleIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRBACDefaultRoleIdRequest.Unmarshal(m, b)
}
func (m *GetRBACDefaultRoleIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRBACDefaultRoleIdRequest.Marshal(b, m, deterministic)
}
func (m *GetRBACDefaultRoleIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRBACDefaultRoleIdRequest.Merge(m, src)
}
func (m *GetRBACDefaultRoleIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetRBACDefaultRoleIdRequest.Size(m)
}
func (m *GetRBACDefaultRoleIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRBACDefaultRoleIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRBACDefaultRoleIdRequest proto.InternalMessageInfo

type GetRBACDefaultRoleIdResponse struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetRBACDefaultRoleIdResponse) Reset()         { *m = GetRBACDefaultRoleIdResponse{} }
func (m *GetRBACDefaultRoleIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetRBACDefaultRoleIdResponse) ProtoMessage()    {}
func (*GetRBACDefaultRoleIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{9}
}

func (m *GetRBACDefaultRoleIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRBACDefaultRoleIdResponse.Unmarshal(m, b)
}
func (m *GetRBACDefaultRoleIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRBACDefaultRoleIdResponse.Marshal(b, m, deterministic)
}
func (m *GetRBACDefaultRoleIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRBACDefaultRoleIdResponse.Merge(m, src)
}
func (m *GetRBACDefaultRoleIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetRBACDefaultRoleIdResponse.Size(m)
}
func (m *GetRBACDefaultRoleIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRBACDefaultRoleIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRBACDefaultRoleIdResponse proto.InternalMessageInfo

func (m *GetRBACDefaultRoleIdResponse) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type SetRBACDefaultRoleIdRequest struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *SetRBACDefaultRoleIdRequest) Reset()         { *m = SetRBACDefaultRoleIdRequest{} }
func (m *SetRBACDefaultRoleIdRequest) String() string { return proto.CompactTextString(m) }
func (*SetRBACDefaultRoleIdRequest) ProtoMessage()    {}
func (*SetRBACDefaultRoleIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{10}
}

func (m *SetRBACDefaultRoleIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRBACDefaultRoleIdRequest.Unmarshal(m, b)
}
func (m *SetRBACDefaultRoleIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRBACDefaultRoleIdRequest.Marshal(b, m, deterministic)
}
func (m *SetRBACDefaultRoleIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRBACDefaultRoleIdRequest.Merge(m, src)
}
func (m *SetRBACDefaultRoleIdRequest) XXX_Size() int {
	return xxx_messageInfo_SetRBACDefaultRoleIdRequest.Size(m)
}
func (m *SetRBACDefaultRoleIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRBACDefaultRoleIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRBACDefaultRoleIdRequest proto.InternalMessageInfo

func (m *SetRBACDefaultRoleIdRequest) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type SetRBACDefaultRoleIdResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *SetRBACDefaultRoleIdResponse) Reset()         { *m = SetRBACDefaultRoleIdResponse{} }
func (m *SetRBACDefaultRoleIdResponse) String() string { return proto.CompactTextString(m) }
func (*SetRBACDefaultRoleIdResponse) ProtoMessage()    {}
func (*SetRBACDefaultRoleIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{11}
}

func (m *SetRBACDefaultRoleIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRBACDefaultRoleIdResponse.Unmarshal(m, b)
}
func (m *SetRBACDefaultRoleIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRBACDefaultRoleIdResponse.Marshal(b, m, deterministic)
}
func (m *SetRBACDefaultRoleIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRBACDefaultRoleIdResponse.Merge(m, src)
}
func (m *SetRBACDefaultRoleIdResponse) XXX_Size() int {
	return xxx_messageInfo_SetRBACDefaultRoleIdResponse.Size(m)
}
func (m *SetRBACDefaultRoleIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRBACDefaultRoleIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetRBACDefaultRoleIdResponse proto.InternalMessageInfo

type GetThreePersonDefaultUserIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetThreePersonDefaultUserIdRequest) Reset()         { *m = GetThreePersonDefaultUserIdRequest{} }
func (m *GetThreePersonDefaultUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetThreePersonDefaultUserIdRequest) ProtoMessage()    {}
func (*GetThreePersonDefaultUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{12}
}

func (m *GetThreePersonDefaultUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThreePersonDefaultUserIdRequest.Unmarshal(m, b)
}
func (m *GetThreePersonDefaultUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThreePersonDefaultUserIdRequest.Marshal(b, m, deterministic)
}
func (m *GetThreePersonDefaultUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThreePersonDefaultUserIdRequest.Merge(m, src)
}
func (m *GetThreePersonDefaultUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetThreePersonDefaultUserIdRequest.Size(m)
}
func (m *GetThreePersonDefaultUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThreePersonDefaultUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetThreePersonDefaultUserIdRequest proto.InternalMessageInfo

type GetThreePersonDefaultUserIdResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-"`
}

func (m *GetThreePersonDefaultUserIdResponse) Reset()         { *m = GetThreePersonDefaultUserIdResponse{} }
func (m *GetThreePersonDefaultUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetThreePersonDefaultUserIdResponse) ProtoMessage()    {}
func (*GetThreePersonDefaultUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_243cb447c0016127, []int{13}
}

func (m *GetThreePersonDefaultUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThreePersonDefaultUserIdResponse.Unmarshal(m, b)
}
func (m *GetThreePersonDefaultUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThreePersonDefaultUserIdResponse.Marshal(b, m, deterministic)
}
func (m *GetThreePersonDefaultUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThreePersonDefaultUserIdResponse.Merge(m, src)
}
func (m *GetThreePersonDefaultUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetThreePersonDefaultUserIdResponse.Size(m)
}
func (m *GetThreePersonDefaultUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThreePersonDefaultUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetThreePersonDefaultUserIdResponse proto.InternalMessageInfo

func (m *GetThreePersonDefaultUserIdResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*GetJobConfigRequest)(nil), "sysconfig.GetJobConfigRequest")
	proto.RegisterType((*GetJobConfigResponse)(nil), "sysconfig.GetJobConfigResponse")
	proto.RegisterType((*SetJobConfigRequest)(nil), "sysconfig.SetJobConfigRequest")
	proto.RegisterType((*SetJobConfigResponse)(nil), "sysconfig.SetJobConfigResponse")
	proto.RegisterType((*GetJobBurstConfigRequest)(nil), "sysconfig.GetJobBurstConfigRequest")
	proto.RegisterType((*GetJobBurstConfigResponse)(nil), "sysconfig.GetJobBurstConfigResponse")
	proto.RegisterType((*SetJobBurstConfigRequest)(nil), "sysconfig.SetJobBurstConfigRequest")
	proto.RegisterType((*SetJobBurstConfigResponse)(nil), "sysconfig.SetJobBurstConfigResponse")
	proto.RegisterType((*GetRBACDefaultRoleIdRequest)(nil), "sysconfig.GetRBACDefaultRoleIdRequest")
	proto.RegisterType((*GetRBACDefaultRoleIdResponse)(nil), "sysconfig.GetRBACDefaultRoleIdResponse")
	proto.RegisterType((*SetRBACDefaultRoleIdRequest)(nil), "sysconfig.SetRBACDefaultRoleIdRequest")
	proto.RegisterType((*SetRBACDefaultRoleIdResponse)(nil), "sysconfig.SetRBACDefaultRoleIdResponse")
	proto.RegisterType((*GetThreePersonDefaultUserIdRequest)(nil), "sysconfig.GetThreePersonDefaultUserIdRequest")
	proto.RegisterType((*GetThreePersonDefaultUserIdResponse)(nil), "sysconfig.GetThreePersonDefaultUserIdResponse")
}

func init() { proto.RegisterFile("sysconfig/sysconfig.proto", fileDescriptor_243cb447c0016127) }

var fileDescriptor_243cb447c0016127 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x5f, 0x6f, 0xda, 0x30,
	0x14, 0xc5, 0xc5, 0x10, 0x6c, 0xb9, 0xe2, 0x65, 0x86, 0xb1, 0x10, 0x18, 0x43, 0x06, 0x6d, 0x48,
	0xdb, 0x98, 0xb4, 0x49, 0xed, 0x5b, 0xa5, 0x42, 0x25, 0xd4, 0xbe, 0x40, 0xe3, 0xf6, 0xb5, 0x15,
	0x94, 0xcb, 0x1f, 0x29, 0x8a, 0xc1, 0x76, 0x1e, 0x90, 0xfa, 0xd5, 0xfa, 0xdd, 0x2a, 0x25, 0x29,
	0x21, 0x4a, 0x9c, 0xa0, 0xbe, 0x61, 0xdf, 0xc3, 0x39, 0xc7, 0xc9, 0xcf, 0x81, 0x86, 0xdc, 0xcb,
	0x27, 0xee, 0x2e, 0x37, 0xab, 0xbf, 0x87, 0x5f, 0x83, 0xad, 0xe0, 0x8a, 0x13, 0xe3, 0xb0, 0x41,
	0xbf, 0x40, 0x75, 0x8c, 0xea, 0x86, 0xcf, 0x47, 0xfe, 0xda, 0xc6, 0x9d, 0x87, 0x52, 0xd1, 0xdf,
	0x50, 0x8b, 0x6f, 0xcb, 0x2d, 0x77, 0x25, 0x92, 0x1a, 0x94, 0x76, 0x1e, 0x7a, 0x68, 0x16, 0x3a,
	0x85, 0xbe, 0x61, 0x07, 0x0b, 0xfa, 0x0b, 0xaa, 0x2c, 0x69, 0xa2, 0x11, 0xd7, 0xa1, 0xc6, 0x52,
	0xac, 0xa9, 0x05, 0x66, 0x10, 0x39, 0xf4, 0x84, 0x54, 0xf1, 0x3a, 0xb7, 0xd0, 0x48, 0x99, 0x85,
	0x9d, 0xea, 0x50, 0x46, 0x77, 0x36, 0x77, 0x82, 0x9c, 0x4f, 0x76, 0xb8, 0x22, 0x2d, 0x30, 0xd4,
	0x5a, 0xa0, 0x5c, 0x73, 0x67, 0x61, 0x7e, 0xe8, 0x14, 0xfa, 0x45, 0x3b, 0xda, 0xa0, 0x53, 0x30,
	0x99, 0x26, 0xee, 0x9d, 0x8e, 0x4d, 0x68, 0x30, 0x5d, 0x49, 0xfa, 0x0d, 0x9a, 0x63, 0x54, 0xf6,
	0xf0, 0x72, 0x74, 0x85, 0xcb, 0x99, 0xe7, 0x28, 0x9b, 0x3b, 0x78, 0xbd, 0x78, 0x3b, 0xe0, 0x39,
	0xb4, 0xd2, 0xc7, 0xe1, 0x19, 0xbf, 0xc2, 0x47, 0xc1, 0x1d, 0x7c, 0xdc, 0x2c, 0xfc, 0x4a, 0x45,
	0xbb, 0x2c, 0x7c, 0x01, 0x3d, 0x83, 0x26, 0xd3, 0xfb, 0xea, 0xff, 0xd7, 0x86, 0x16, 0xcb, 0x08,
	0xa4, 0x3d, 0xa0, 0x63, 0x54, 0x77, 0x6b, 0x81, 0x38, 0x45, 0x21, 0xb9, 0x1b, 0xca, 0xee, 0x25,
	0x8a, 0xa8, 0xf6, 0x05, 0x74, 0x33, 0x55, 0x51, 0x7b, 0x4f, 0xa2, 0x38, 0x6a, 0xe1, 0xf9, 0x82,
	0x7f, 0x2f, 0x25, 0x30, 0xd8, 0x5e, 0x06, 0xcf, 0x8a, 0x4c, 0xa0, 0x72, 0x0c, 0x1d, 0x69, 0x0f,
	0x22, 0x70, 0x53, 0x20, 0xb5, 0xbe, 0x6b, 0xe7, 0x61, 0xee, 0x04, 0x2a, 0x4c, 0x67, 0xc8, 0x72,
	0x0c, 0xd3, 0x18, 0x25, 0x0f, 0xf0, 0x39, 0xc1, 0x21, 0xe9, 0x26, 0x6a, 0x24, 0x91, 0xb2, 0x7a,
	0xd9, 0xa2, 0xc8, 0x9f, 0x65, 0xfa, 0xb3, 0x53, 0xfc, 0xb5, 0x14, 0x92, 0x95, 0x7f, 0xad, 0x13,
	0x6f, 0x9d, 0xfc, 0x88, 0xb7, 0xd3, 0xe1, 0x64, 0xfd, 0xcc, 0xd5, 0x45, 0x41, 0x2c, 0x2f, 0x88,
	0x9d, 0x18, 0x94, 0xc5, 0x29, 0x79, 0xf6, 0xef, 0x95, 0x8e, 0x40, 0xf2, 0x27, 0x5e, 0x38, 0x87,
	0x67, 0x6b, 0x70, 0xaa, 0x3c, 0x48, 0x9f, 0x97, 0xfd, 0xef, 0xe9, 0xff, 0xd7, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xcc, 0xd0, 0x7a, 0x0a, 0x6c, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SysConfigClient is the client API for SysConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SysConfigClient interface {
	GetJobConfig(ctx context.Context, in *GetJobConfigRequest, opts ...grpc.CallOption) (*GetJobConfigResponse, error)
	SetJobConfig(ctx context.Context, in *SetJobConfigRequest, opts ...grpc.CallOption) (*SetJobConfigResponse, error)
	GetJobBurstConfig(ctx context.Context, in *GetJobBurstConfigRequest, opts ...grpc.CallOption) (*GetJobBurstConfigResponse, error)
	SetJobBurstConfig(ctx context.Context, in *SetJobBurstConfigRequest, opts ...grpc.CallOption) (*SetJobBurstConfigResponse, error)
	GetRBACDefaultRoleId(ctx context.Context, in *GetRBACDefaultRoleIdRequest, opts ...grpc.CallOption) (*GetRBACDefaultRoleIdResponse, error)
	SetRBACDefaultRoleId(ctx context.Context, in *SetRBACDefaultRoleIdRequest, opts ...grpc.CallOption) (*SetRBACDefaultRoleIdResponse, error)
	GetThreePersonDefaultUserId(ctx context.Context, in *GetThreePersonDefaultUserIdRequest, opts ...grpc.CallOption) (*GetThreePersonDefaultUserIdResponse, error)
}

type sysConfigClient struct {
	cc *grpc.ClientConn
}

func NewSysConfigClient(cc *grpc.ClientConn) SysConfigClient {
	return &sysConfigClient{cc}
}

func (c *sysConfigClient) GetJobConfig(ctx context.Context, in *GetJobConfigRequest, opts ...grpc.CallOption) (*GetJobConfigResponse, error) {
	out := new(GetJobConfigResponse)
	err := c.cc.Invoke(ctx, "/sysconfig.SysConfig/GetJobConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysConfigClient) SetJobConfig(ctx context.Context, in *SetJobConfigRequest, opts ...grpc.CallOption) (*SetJobConfigResponse, error) {
	out := new(SetJobConfigResponse)
	err := c.cc.Invoke(ctx, "/sysconfig.SysConfig/SetJobConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysConfigClient) GetJobBurstConfig(ctx context.Context, in *GetJobBurstConfigRequest, opts ...grpc.CallOption) (*GetJobBurstConfigResponse, error) {
	out := new(GetJobBurstConfigResponse)
	err := c.cc.Invoke(ctx, "/sysconfig.SysConfig/GetJobBurstConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysConfigClient) SetJobBurstConfig(ctx context.Context, in *SetJobBurstConfigRequest, opts ...grpc.CallOption) (*SetJobBurstConfigResponse, error) {
	out := new(SetJobBurstConfigResponse)
	err := c.cc.Invoke(ctx, "/sysconfig.SysConfig/SetJobBurstConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysConfigClient) GetRBACDefaultRoleId(ctx context.Context, in *GetRBACDefaultRoleIdRequest, opts ...grpc.CallOption) (*GetRBACDefaultRoleIdResponse, error) {
	out := new(GetRBACDefaultRoleIdResponse)
	err := c.cc.Invoke(ctx, "/sysconfig.SysConfig/GetRBACDefaultRoleId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysConfigClient) SetRBACDefaultRoleId(ctx context.Context, in *SetRBACDefaultRoleIdRequest, opts ...grpc.CallOption) (*SetRBACDefaultRoleIdResponse, error) {
	out := new(SetRBACDefaultRoleIdResponse)
	err := c.cc.Invoke(ctx, "/sysconfig.SysConfig/SetRBACDefaultRoleId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysConfigClient) GetThreePersonDefaultUserId(ctx context.Context, in *GetThreePersonDefaultUserIdRequest, opts ...grpc.CallOption) (*GetThreePersonDefaultUserIdResponse, error) {
	out := new(GetThreePersonDefaultUserIdResponse)
	err := c.cc.Invoke(ctx, "/sysconfig.SysConfig/GetThreePersonDefaultUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysConfigServer is the server API for SysConfig service.
type SysConfigServer interface {
	GetJobConfig(context.Context, *GetJobConfigRequest) (*GetJobConfigResponse, error)
	SetJobConfig(context.Context, *SetJobConfigRequest) (*SetJobConfigResponse, error)
	GetJobBurstConfig(context.Context, *GetJobBurstConfigRequest) (*GetJobBurstConfigResponse, error)
	SetJobBurstConfig(context.Context, *SetJobBurstConfigRequest) (*SetJobBurstConfigResponse, error)
	GetRBACDefaultRoleId(context.Context, *GetRBACDefaultRoleIdRequest) (*GetRBACDefaultRoleIdResponse, error)
	SetRBACDefaultRoleId(context.Context, *SetRBACDefaultRoleIdRequest) (*SetRBACDefaultRoleIdResponse, error)
	GetThreePersonDefaultUserId(context.Context, *GetThreePersonDefaultUserIdRequest) (*GetThreePersonDefaultUserIdResponse, error)
}

// UnimplementedSysConfigServer can be embedded to have forward compatible implementations.
type UnimplementedSysConfigServer struct {
}

func (*UnimplementedSysConfigServer) GetJobConfig(ctx context.Context, req *GetJobConfigRequest) (*GetJobConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobConfig not implemented")
}
func (*UnimplementedSysConfigServer) SetJobConfig(ctx context.Context, req *SetJobConfigRequest) (*SetJobConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetJobConfig not implemented")
}
func (*UnimplementedSysConfigServer) GetJobBurstConfig(ctx context.Context, req *GetJobBurstConfigRequest) (*GetJobBurstConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobBurstConfig not implemented")
}
func (*UnimplementedSysConfigServer) SetJobBurstConfig(ctx context.Context, req *SetJobBurstConfigRequest) (*SetJobBurstConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetJobBurstConfig not implemented")
}
func (*UnimplementedSysConfigServer) GetRBACDefaultRoleId(ctx context.Context, req *GetRBACDefaultRoleIdRequest) (*GetRBACDefaultRoleIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRBACDefaultRoleId not implemented")
}
func (*UnimplementedSysConfigServer) SetRBACDefaultRoleId(ctx context.Context, req *SetRBACDefaultRoleIdRequest) (*SetRBACDefaultRoleIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRBACDefaultRoleId not implemented")
}
func (*UnimplementedSysConfigServer) GetThreePersonDefaultUserId(ctx context.Context, req *GetThreePersonDefaultUserIdRequest) (*GetThreePersonDefaultUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThreePersonDefaultUserId not implemented")
}

func RegisterSysConfigServer(s *grpc.Server, srv SysConfigServer) {
	s.RegisterService(&_SysConfig_serviceDesc, srv)
}

func _SysConfig_GetJobConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).GetJobConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysconfig.SysConfig/GetJobConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).GetJobConfig(ctx, req.(*GetJobConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysConfig_SetJobConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetJobConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).SetJobConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysconfig.SysConfig/SetJobConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).SetJobConfig(ctx, req.(*SetJobConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysConfig_GetJobBurstConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobBurstConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).GetJobBurstConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysconfig.SysConfig/GetJobBurstConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).GetJobBurstConfig(ctx, req.(*GetJobBurstConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysConfig_SetJobBurstConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetJobBurstConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).SetJobBurstConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysconfig.SysConfig/SetJobBurstConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).SetJobBurstConfig(ctx, req.(*SetJobBurstConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysConfig_GetRBACDefaultRoleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRBACDefaultRoleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).GetRBACDefaultRoleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysconfig.SysConfig/GetRBACDefaultRoleId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).GetRBACDefaultRoleId(ctx, req.(*GetRBACDefaultRoleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysConfig_SetRBACDefaultRoleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRBACDefaultRoleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).SetRBACDefaultRoleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysconfig.SysConfig/SetRBACDefaultRoleId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).SetRBACDefaultRoleId(ctx, req.(*SetRBACDefaultRoleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysConfig_GetThreePersonDefaultUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreePersonDefaultUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysConfigServer).GetThreePersonDefaultUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysconfig.SysConfig/GetThreePersonDefaultUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysConfigServer).GetThreePersonDefaultUserId(ctx, req.(*GetThreePersonDefaultUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SysConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sysconfig.SysConfig",
	HandlerType: (*SysConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJobConfig",
			Handler:    _SysConfig_GetJobConfig_Handler,
		},
		{
			MethodName: "SetJobConfig",
			Handler:    _SysConfig_SetJobConfig_Handler,
		},
		{
			MethodName: "GetJobBurstConfig",
			Handler:    _SysConfig_GetJobBurstConfig_Handler,
		},
		{
			MethodName: "SetJobBurstConfig",
			Handler:    _SysConfig_SetJobBurstConfig_Handler,
		},
		{
			MethodName: "GetRBACDefaultRoleId",
			Handler:    _SysConfig_GetRBACDefaultRoleId_Handler,
		},
		{
			MethodName: "SetRBACDefaultRoleId",
			Handler:    _SysConfig_SetRBACDefaultRoleId_Handler,
		},
		{
			MethodName: "GetThreePersonDefaultUserId",
			Handler:    _SysConfig_GetThreePersonDefaultUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysconfig/sysconfig.proto",
}
