// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/zone/zone.proto

package zone

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListZoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListZoneRequest) Reset() {
	*x = ListZoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zone_zone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZoneRequest) ProtoMessage() {}

func (x *ListZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZoneRequest.ProtoReflect.Descriptor instead.
func (*ListZoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{0}
}

type ListZoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Zones map[string]*Zone `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ListZoneResponse) Reset() {
	*x = ListZoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zone_zone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZoneResponse) ProtoMessage() {}

func (x *ListZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZoneResponse.ProtoReflect.Descriptor instead.
func (*ListZoneResponse) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{1}
}

func (x *ListZoneResponse) GetZones() map[string]*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

type Zone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HpcEndpoint     string `protobuf:"bytes,1,opt,name=hpc_endpoint,json=hpcEndpoint,proto3" json:"hpc_endpoint,omitempty"`
	StorageEndpoint string `protobuf:"bytes,2,opt,name=storage_endpoint,json=storageEndpoint,proto3" json:"storage_endpoint,omitempty"`
	CloudAppEnable  bool   `protobuf:"varint,3,opt,name=cloud_app_enable,json=cloudAppEnable,proto3" json:"cloud_app_enable,omitempty"`
}

func (x *Zone) Reset() {
	*x = Zone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_zone_zone_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{2}
}

func (x *Zone) GetHpcEndpoint() string {
	if x != nil {
		return x.HpcEndpoint
	}
	return ""
}

func (x *Zone) GetStorageEndpoint() string {
	if x != nil {
		return x.StorageEndpoint
	}
	return ""
}

func (x *Zone) GetCloudAppEnable() bool {
	if x != nil {
		return x.CloudAppEnable
	}
	return false
}

var File_proto_zone_zone_proto protoreflect.FileDescriptor

var file_proto_zone_zone_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x6f, 0x6e, 0x65, 0x2f, 0x7a, 0x6f, 0x6e,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x93,
	0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x7a, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x5a,
	0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x5a, 0x6f, 0x6e, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x7a, 0x6f, 0x6e, 0x65, 0x73, 0x1a, 0x45, 0x0a,
	0x0a, 0x5a, 0x6f, 0x6e, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x7e, 0x0a, 0x04, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x68, 0x70, 0x63, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x68, 0x70, 0x63, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x29, 0x0a, 0x10, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x41, 0x70, 0x70, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x32, 0x4d, 0x0a, 0x0b, 0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x5a, 0x6f, 0x6e, 0x65, 0x73,
	0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x5a, 0x6f, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x2e, 0x79, 0x75, 0x61, 0x6e, 0x73,
	0x75, 0x61, 0x6e, 0x2e, 0x63, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x72,
	0x6f, 0x6f, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x6f,
	0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_zone_zone_proto_rawDescOnce sync.Once
	file_proto_zone_zone_proto_rawDescData = file_proto_zone_zone_proto_rawDesc
)

func file_proto_zone_zone_proto_rawDescGZIP() []byte {
	file_proto_zone_zone_proto_rawDescOnce.Do(func() {
		file_proto_zone_zone_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_zone_zone_proto_rawDescData)
	})
	return file_proto_zone_zone_proto_rawDescData
}

var file_proto_zone_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_zone_zone_proto_goTypes = []interface{}{
	(*ListZoneRequest)(nil),  // 0: proto.ListZoneRequest
	(*ListZoneResponse)(nil), // 1: proto.ListZoneResponse
	(*Zone)(nil),             // 2: proto.Zone
	nil,                      // 3: proto.ListZoneResponse.ZonesEntry
}
var file_proto_zone_zone_proto_depIdxs = []int32{
	3, // 0: proto.ListZoneResponse.zones:type_name -> proto.ListZoneResponse.ZonesEntry
	2, // 1: proto.ListZoneResponse.ZonesEntry.value:type_name -> proto.Zone
	0, // 2: proto.ZoneService.ListZones:input_type -> proto.ListZoneRequest
	1, // 3: proto.ZoneService.ListZones:output_type -> proto.ListZoneResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_zone_zone_proto_init() }
func file_proto_zone_zone_proto_init() {
	if File_proto_zone_zone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_zone_zone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListZoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zone_zone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListZoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_zone_zone_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Zone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_zone_zone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_zone_zone_proto_goTypes,
		DependencyIndexes: file_proto_zone_zone_proto_depIdxs,
		MessageInfos:      file_proto_zone_zone_proto_msgTypes,
	}.Build()
	File_proto_zone_zone_proto = out.File
	file_proto_zone_zone_proto_rawDesc = nil
	file_proto_zone_zone_proto_goTypes = nil
	file_proto_zone_zone_proto_depIdxs = nil
}
